services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: eco-backend:latest
    env_file: docker-compose.env
    environment:
      SERVICES: api
      API_PORT: 3500
      WEB_PORT: 3500
    ports:
      - "3502:3500"
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3500"
    networks:
      - internal

  greeter:
    image: eco-backend:latest
    env_file: docker-compose.env
    environment:
      SERVICES: greeter
    depends_on:
      - api
      - nats
    networks:
      - internal

  products:
    image: eco-backend:latest
    env_file: docker-compose.env
    environment:
      SERVICES: products
    depends_on:
      - api
      - nats
    networks:
      - internal

  users:
    image: eco-backend:latest
    env_file: docker-compose.env
    environment:
      SERVICES: users
    depends_on:
      - api
      - nats
    networks:
      - internal

  auth:
    image: eco-backend:latest
    env_file: docker-compose.env
    environment:
      SERVICES: auth
    depends_on:
      - api
      - nats
    networks:
      - internal

  web:
    image: eco-backend:latest
    env_file: docker-compose.env
    environment:
      SERVICES: web
      WEB_PORT: 3500
    ports:
      - "3501:3500"
    depends_on:
      - api
      - nats
    networks:
      - internal

  nats:
    image: nats:2
    networks:
      - internal

  traefik:
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "3503:80"
      - "3001:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default

networks:
  internal:

volumes:
  data: